# NAS (fnos) Docker 配置

# PostgreSQL
POSTGRES_PORT=5433
POSTGRES_USER=chatbot
POSTGRES_PASSWORD=chatbot
POSTGRES_DB=chatbot
POSTGRES_DATA_PATH=/vol1/1000/SoftDisk/docker/postgres

# MySQL (未部署)
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=chatbot
MYSQL_DATABASE=chatbot
MYSQL_USER=chatbot
MYSQL_PASSWORD=chatbot
MYSQL_DATA_PATH=/vol1/1000/SoftDisk/docker/mysql

# Milvus
MILVUS_PORT=19530
MILVUS_API_PORT=9091
