/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentEditor: typeof import('./components/agent/AgentEditor.vue')['default']
    AgentIndicator: typeof import('./components/chat/AgentIndicator.vue')['default']
    AgentSelector: typeof import('./components/agent/AgentSelector.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    ChatContainer: typeof import('./components/chat/ChatContainer.vue')['default']
    DirectoryBrowser: typeof import('./components/settings/DirectoryBrowser.vue')['default']
    ExecutionHistory: typeof import('./components/cron-job/ExecutionHistory.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JobForm: typeof import('./components/cron-job/JobForm.vue')['default']
    JobStatusBadge: typeof import('./components/cron-job/JobStatusBadge.vue')['default']
    MessageInput: typeof import('./components/chat/MessageInput.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    ModelSelector: typeof import('./components/chat/ModelSelector.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NotificationBell: typeof import('./components/common/NotificationBell.vue')['default']
    NotificationToast: typeof import('./components/common/NotificationToast.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleEditor: typeof import('./components/rules/RuleEditor.vue')['default']
    RuleItem: typeof import('./components/rules/RuleItem.vue')['default']
    SessionList: typeof import('./components/chat/SessionList.vue')['default']
    SystemSettingsPane: typeof import('./components/settings/SystemSettingsPane.vue')['default']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
    ToolCallBlock: typeof import('./components/chat/ToolCallBlock.vue')['default']
  }
}
