/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentEditor: typeof import('./components/agent/AgentEditor.vue')['default']
    AgentSelector: typeof import('./components/agent/AgentSelector.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    ChatContainer: typeof import('./components/chat/ChatContainer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageInput: typeof import('./components/chat/MessageInput.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleEditor: typeof import('./components/rules/RuleEditor.vue')['default']
    RuleItem: typeof import('./components/rules/RuleItem.vue')['default']
    SessionList: typeof import('./components/chat/SessionList.vue')['default']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
  }
}
